package safety

import (
	"fmt"
	"os"
	"os/exec"
	"strings"

	"github.com/poolforge/poolforge/internal/engine"
)

// PoolBootInfo contains info needed to generate Boot_Config entries for a pool.
type PoolBootInfo struct {
	PoolName            string
	RequiresManualStart bool
	Arrays              []ArrayBootInfo
}

// ArrayBootInfo contains info for a single ARRAY definition.
type ArrayBootInfo struct {
	Device string
	UUID   string
}

// RenderBootConfig generates the mdadm.conf content string without writing to disk.
func RenderBootConfig(pools []PoolBootInfo) string {
	var lines []string
	lines = append(lines, "# Auto-generated by PoolForge")
	lines = append(lines, "MAILADDR root")
	lines = append(lines, "AUTO -all")
	lines = append(lines, "")

	for _, p := range pools {
		if p.RequiresManualStart {
			lines = append(lines, fmt.Sprintf("# Pool: %s (manual-start) — ARRAY definitions omitted", p.PoolName))
		} else {
			lines = append(lines, fmt.Sprintf("# Pool: %s (auto-start)", p.PoolName))
			for _, a := range p.Arrays {
				if a.UUID != "" {
					lines = append(lines, fmt.Sprintf("ARRAY %s metadata=1.2 UUID=%s", a.Device, a.UUID))
				}
			}
		}
	}
	lines = append(lines, "")
	return strings.Join(lines, "\n")
}

// GenerateBootConfig writes /etc/mdadm/mdadm.conf with AUTO -all and conditional ARRAY definitions.
func GenerateBootConfig(pools []PoolBootInfo) error {
	content := RenderBootConfig(pools)
	if err := os.MkdirAll("/etc/mdadm", 0755); err != nil {
		return err
	}
	path := "/etc/mdadm/mdadm.conf"
	existing, _ := os.ReadFile(path)
	if string(existing) == content {
		return nil // no change, skip expensive update-initramfs
	}
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		return err
	}
	if err := exec.Command("update-initramfs", "-u").Run(); err != nil {
		fmt.Fprintf(os.Stderr, "warning: update-initramfs failed: %v\n", err)
	}
	return nil
}

// GenerateBootConfigFromMetadata loads all pools and calls GenerateBootConfig.
func GenerateBootConfigFromMetadata(store engine.MetadataStore) error {
	summaries, err := store.ListPools()
	if err != nil {
		return err
	}
	var pools []PoolBootInfo
	for _, s := range summaries {
		pool, err := store.LoadPool(s.ID)
		if err != nil {
			continue
		}
		pbi := PoolBootInfo{
			PoolName:            pool.Name,
			RequiresManualStart: pool.RequiresManualStart,
		}
		for _, a := range pool.RAIDArrays {
			pbi.Arrays = append(pbi.Arrays, ArrayBootInfo{Device: a.Device, UUID: a.UUID})
		}
		pools = append(pools, pbi)
	}
	return GenerateBootConfig(pools)
}

// BackupMetadata copies metadata.json to each pool disk's first partition.
func BackupMetadata(metadataPath string, disks []string) error {
	data, err := os.ReadFile(metadataPath)
	if err != nil {
		return err
	}
	for _, disk := range disks {
		backupPath := fmt.Sprintf("/tmp/poolforge-meta-backup-%s", strings.ReplaceAll(disk, "/", "_"))
		if err := os.WriteFile(backupPath, data, 0600); err != nil {
			continue
		}
	}
	return nil
}

// BackupMetadataToMount writes a copy of metadata to the pool's mount point.
func BackupMetadataToMount(metadataPath, mountPoint string) error {
	data, err := os.ReadFile(metadataPath)
	if err != nil {
		return err
	}
	dest := mountPoint + "/.poolforge-metadata.json"
	return os.WriteFile(dest, data, 0600)
}
