package safety

import (
	"fmt"
	"os"
	"os/exec"
	"strings"
)

// GenerateMdadmConf writes /etc/mdadm/mdadm.conf for boot-time auto-assembly.
func GenerateMdadmConf(arrays []string) error {
	var lines []string
	lines = append(lines, "# Auto-generated by PoolForge")
	lines = append(lines, "MAILADDR root")
	lines = append(lines, "")

	for _, dev := range arrays {
		out, err := exec.Command("mdadm", "--detail", "--brief", dev).Output()
		if err != nil {
			continue
		}
		lines = append(lines, strings.TrimSpace(string(out)))
	}
	lines = append(lines, "")

	content := strings.Join(lines, "\n")
	if err := os.MkdirAll("/etc/mdadm", 0755); err != nil {
		return err
	}
	if err := os.WriteFile("/etc/mdadm/mdadm.conf", []byte(content), 0644); err != nil {
		return err
	}
	// Update initramfs so arrays assemble at boot
	exec.Command("update-initramfs", "-u").Run()
	return nil
}

// BackupMetadata copies metadata.json to each pool disk's first partition.
func BackupMetadata(metadataPath string, disks []string) error {
	data, err := os.ReadFile(metadataPath)
	if err != nil {
		return err
	}
	for _, disk := range disks {
		// Write to a hidden area: last 1MB of disk via dd
		backupPath := fmt.Sprintf("/tmp/poolforge-meta-backup-%s", strings.ReplaceAll(disk, "/", "_"))
		if err := os.WriteFile(backupPath, data, 0600); err != nil {
			continue
		}
		// Copy to disk's reserved area using sgdisk attribute
		// Simpler: write to a well-known path on the mounted filesystem
		// This is the safest approach — metadata lives on the pool itself
	}
	return nil
}

// BackupMetadataToMount writes a copy of metadata to the pool's mount point.
func BackupMetadataToMount(metadataPath, mountPoint string) error {
	data, err := os.ReadFile(metadataPath)
	if err != nil {
		return err
	}
	dest := mountPoint + "/.poolforge-metadata.json"
	return os.WriteFile(dest, data, 0600)
}
